### ISSUE TITLE
Feature request: re-run older job

### ISSUE THREAD

**Issue by artem-yushkovsky** [neuro-inc/platform-client-python#1963]
Feature request: 
- `neuro rerun <job-ID-or-name>` to print the line used for restart the same job
- `neuro rerun <job-ID-or-name> --print-only` only prints the line (so that I can edit it and start again).

Claim: this functionality will ease the work with the platform significantly.

Use-cases:
1. My very common use-case: One of the jobs I ran failed, I fix code locally, upload it and want to re-run the same job again with absolutely the same parameters
2. A user asks me to debug their failed job, I re-run it to reproduce or at least to see the line how to reproduce.

**Comment by serhiy-storchaka** [comment]
The first case is redundant, because you always can run a command line produced by a command:
```
$(neuro job generate-run-command <job-ID-or-name>)
```
So I think we only need a command which generates a command to run a job with the same options.

**Comment by romasku** [comment]
It will not work as expected for some complex cases. For example, if
```
$ neuro job generate-run-commnad some-job
neuro run ubuntu:latest /bin/bash -c 'ls -l && pwd'
```
The `$(...)` will fail because of some weirdness in how bash works with quotes (tested locally). Please check [this SO question](https://stackoverflow.com/questions/11079342/execute-command-containing-quotes-from-shell-variable) for some more info, I personally do not know bash well enough. 
Though, looks like it will work with `eval`: 
```
eval $(neuro job rerun-command test-rerun2)
```
